
import { Package } from './types';

export const preweddingImageUrls: string[] = [
    "https://i.ibb.co/67KPvBw9/AODAI9.jpg", "https://i.ibb.co/20vfccd7/AODAI10.jpg", "https://i.ibb.co/hTfhc5B/CHILINH1.jpg", 
    "https://i.ibb.co/qMymn3ZN/CHILINH2.jpg", "https://i.ibb.co/yBd3t1pV/CHILINH3.jpg", "https://i.ibb.co/v4bQ1Q3s/CHILINH4.jpg", 
    "https://i.ibb.co/gZBNQQQG/CHILINH5.jpg", "https://i.ibb.co/yBVYmMmH/CHILINH6.jpg", "https://i.ibb.co/rfsLHXSd/CHILINH7.jpg", 
    "https://i.ibb.co/1JG4W97x/CHILINH8.jpg", "https://i.ibb.co/KcxpBJ6V/CHILINH9.jpg", "https://i.ibb.co/jvd0wbFb/CHILINH10.jpg", 
    "https://i.ibb.co/yFVTnqqf/CONCEPT1.jpg", "https://i.ibb.co/4gnJtJ2y/CONCEPT2.jpg", "https://i.ibb.co/57pYLLb/CONCEPT3.jpg", 
    "https://i.ibb.co/BH8Nkgfq/CONCEPT4.jpg", "https://i.ibb.co/HfSjnqq9/CONCEPT5.jpg", "https://i.ibb.co/mCX64BdN/CONCEPT6.jpg", 
    "https://i.ibb.co/KzzVH8kD/CONCEPT7.jpg", "https://i.ibb.co/NgZXNp9x/CONCEPT8.jpg", "https://i.ibb.co/Gv8xbWDs/CONCEPT9.jpg", 
    "https://i.ibb.co/99Gzh3Kc/CONCEPT10.jpg", "https://i.ibb.co/2Y53TMp3/CONCEPT11.jpg", "https://i.ibb.co/mm4H51W/CONCEPT12.jpg", 
    "https://i.ibb.co/84bLDy5d/DANGOAI1.jpg", "https://i.ibb.co/GfF6CwWJ/DANGOAI2.jpg", "https://i.ibb.co/mCvxBzZz/DANGOAI4.jpg", 
    "https://i.ibb.co/7J5Sz0t5/DANGOAI5.jpg", "https://i.ibb.co/CKR1dbtn/DANGOAI6.jpg", "https://i.ibb.co/v6MgzNFJ/DANGOAI9.jpg", 
    "https://i.ibb.co/nNSRcBPn/DANGOAI10.jpg", "https://i.ibb.co/CszWMTmW/HDCAFE1.jpg", "https://i.ibb.co/Dfg5B891/HDCAFE2.jpg", 
    "https://i.ibb.co/FkJfgrdm/HDCAFE3.jpg", "https://i.ibb.co/fzNMRZ6H/HDCAFE4.jpg", "https://i.ibb.co/LD2qn6xD/HDCAFE5.jpg", 
    "https://i.ibb.co/C3JhqK7X/HDCAFE6.jpg", "https://i.ibb.co/yF9WrYgk/HDCAFE7.jpg", "https://i.ibb.co/j98nbSY9/HDCAFE8.jpg", 
    "https://i.ibb.co/SwSVD5V8/HDCAFE9.jpg", "https://i.ibb.co/0yvBrCbL/HDNGOAITROI1.jpg", "https://i.ibb.co/3m8nFxGD/HDNGOAITROI2.jpg", 
    "https://i.ibb.co/WvGp8dmY/HDNGOAITROI3.jpg", "https://i.ibb.co/zWWzs6VM/HDNGOAITROI4.jpg", "https://i.ibb.co/7J0f3W4H/HDNGOAITROI5.jpg", 
    "https://i.ibb.co/gZ3yTS79/HDNGOAITROI6.jpg", "https://i.ibb.co/QFTZD87W/HDNGOAITROI7.jpg", "https://i.ibb.co/nq8sJ4CY/HDNGOAITROI8.jpg", 
    "https://i.ibb.co/8n7G63P2/HDNGOAITROI9.jpg", "https://i.ibb.co/pvMnnv8F/HDNGOAITROI10.jpg", "https://i.ibb.co/rqwCHS3/HDNGOAITROI11.jpg", 
    "https://i.ibb.co/RpG1hqJf/HDNGOAITROI12.jpg", "https://i.ibb.co/M5kXLb77/HDNGOAITROI13.jpg", "https://i.ibb.co/qK2GJfz/LUX1.jpg", 
    "https://i.ibb.co/x8qLZbRt/LUX2.jpg", "https://i.ibb.co/mVBQN8T3/LUX3.jpg", "https://i.ibb.co/9kRkF9f5/LUX4.jpg", 
    "https://i.ibb.co/wFsYKd6d/LUX5.jpg", "https://i.ibb.co/67Z8q37N/LUX6.jpg", "https://i.ibb.co/VcxHgRj5/PHIMTRUONGHD1.jpg", 
    "https://i.ibb.co/jk9JVvw8/PHIMTRUONGHD2.jpg", "https://i.ibb.co/7DXVzR4/PHIMTRUONGHD3.jpg", "https://i.ibb.co/KC3MJg5/PHIMTRUONGHD4.jpg", 
    "https://i.ibb.co/6JGFhCrS/PHIMTRUONGHD5.jpg", "https://i.ibb.co/TBGk6Q8p/PHIMTRUONGHD6.jpg", "https://i.ibb.co/20wnphtf/PHIMTRUONGHD7.jpg", 
    "https://i.ibb.co/YT3d6N1D/PHIMTRUONGHD8.jpg", "https://i.ibb.co/7thc8n00/PHIMTRUONGHD9.jpg", "https://i.ibb.co/XnY9S2R/PHIMTRUONGHD10.jpg", 
    "https://i.ibb.co/RTJVWWP5/PHIMTRUONGHD11.jpg", "https://i.ibb.co/bg4dH4qp/STUDIOS1.jpg", "https://i.ibb.co/rRnQRy8g/STUDIOS2.jpg", 
    "https://i.ibb.co/pBfRvWvQ/STUDIOS3.jpg", "https://i.ibb.co/NnVk3Y03/STUDIOS4.jpg", "https://i.ibb.co/bjp9zW2y/STUDIOS5.jpg", 
    "https://i.ibb.co/3Yycsmbc/STUDIOS6.jpg", "https://i.ibb.co/p6txHKFc/STUDIOS7.jpg", "https://i.ibb.co/VWjLtR8k/STUDIOS8.jpg", 
    "https://i.ibb.co/TGPBX57/STUDIOS9.jpg", "https://i.ibb.co/b5FzV9Lv/STUDIOS10.jpg", "https://i.ibb.co/6cZwTkqj/STUDIOS11.jpg", 
    "https://i.ibb.co/WNVxMfYL/STUDIOS12.jpg", "https://i.ibb.co/cS3N6FND/STUDIOS13.jpg", "https://i.ibb.co/f38q7LC/STUDIOS14.jpg", 
    "https://i.ibb.co/21WH8vmW/STUDIOS15.jpg", "https://i.ibb.co/JRY31VBF/STUDIOS16.jpg", "https://i.ibb.co/HTjwX2SX/STUDIOS17.jpg", 
    "https://i.ibb.co/GQ1Y6qrT/STUDIOS18.jpg", "https://i.ibb.co/fGYPZtRk/STUDIOS19.jpg", "https://i.ibb.co/RGPqkvtm/STUDIOS20.jpg", 
    "https://i.ibb.co/HfSyL8LP/STUDIOS21.jpg"
];

export const eventImageUrls: string[] = [
    "https://i.ibb.co/k2TmB7cs/LUCIEPSC2.jpg", "https://i.ibb.co/ymvVwksK/LUCIEPSC1.jpg", "https://i.ibb.co/1GjqzbCF/LUCIEPSC3.jpg", 
    "https://i.ibb.co/wZw7SJpb/LUCIEPSC4.jpg", "https://i.ibb.co/pBsNmj1V/LUCIEPSC5.jpg", "https://i.ibb.co/yBQk75k9/LUCIEPSC6.jpg", 
    "https://i.ibb.co/QFW5ThFx/LUCIEPSC7.jpg", "https://i.ibb.co/YFh6PSRV/LUCIEPSC8.jpg", "https://i.ibb.co/hJgCcX2q/LUCIEPSC9.jpg", 
    "https://i.ibb.co/YFQGQ3jd/LUCIEPSC10.jpg", "https://i.ibb.co/rfHxjkLS/LUCIEPSC11.jpg", "https://i.ibb.co/3YktDPdR/LUCIEPSC12.jpg", 
    "https://i.ibb.co/1Dk8L2L/LUCIEPSC13.jpg", "https://i.ibb.co/s9TCsVFk/LUCIEPSC14.jpg", "https://i.ibb.co/MkKD8ZWZ/LUCIEPSC15.jpg", 
    "https://i.ibb.co/Y4xyPDzG/LUCIEPSC16.jpg", "https://i.ibb.co/M5275vSd/LUCIEPSC17.jpg", "https://i.ibb.co/6cLJk3Bw/LUCIEPSC18.jpg", 
    "https://i.ibb.co/Y4zrRtgC/LUCIEPSC19.jpg", "https://i.ibb.co/8L6yYMB5/LUCIEPSC20.jpg", "https://i.ibb.co/93ybG3rQ/LUCIEPSC21.jpg", 
    "https://i.ibb.co/chxzbMk5/LUCIEPSC22.jpg", "https://i.ibb.co/JR58tBRt/LUCIEPSC23.jpg", "https://i.ibb.co/rGsZpPt0/LUCIEPSC24.jpg", 
    "https://i.ibb.co/XkCkjxWf/LUCIEPSC25.jpg", "https://i.ibb.co/Kd8pjy0/LUCIEPSC26.jpg", "https://i.ibb.co/dwQf3zmw/LUCIEPSC27.jpg", 
    "https://i.ibb.co/DfV6QqDD/LUCIEPSC28.jpg", "https://i.ibb.co/fYkvZSjP/LUCIEPSC29.jpg", "https://i.ibb.co/Xr0F8dTY/LUCIEPSC30.jpg", 
    "https://i.ibb.co/pvDBj8Rp/LUCIEPSC31.jpg", "https://i.ibb.co/rfHNTJCK/LUCIEPSC32.jpg", "https://i.ibb.co/6JnRd440/LUCIEPSC33.jpg", 
    "https://i.ibb.co/mCCjfHpw/LUCIEPSC34.jpg", "https://i.ibb.co/C53HfFbp/LUCIEPSC35.jpg", "https://i.ibb.co/216WgJM7/LUCIEPSC36.jpg", 
    "https://i.ibb.co/mC6XN7sP/LUCIEPSC37.jpg", "https://i.ibb.co/Nd97r0yt/LUCIEPSC38.jpg", "https://i.ibb.co/XZb4NnMx/LUCIEPSC39.jpg", 
    "https://i.ibb.co/nxRjSQK/LUCIEPSC40.jpg", "https://i.ibb.co/bMpyfMr2/LUCIEPSC41.jpg", "https://i.ibb.co/hFg7pNym/LUCIEPSC42.jpg", 
    "https://i.ibb.co/xnCQyY1/LUCIEPSC43.jpg", "https://i.ibb.co/hRB2Dk9J/LUCIEPSC45.jpg", "https://i.ibb.co/svL1jyy3/LUCIEPSC44.jpg", 
    "https://i.ibb.co/WvV4LcC7/LUCIEPSC46.jpg", "https://i.ibb.co/GfbLm91z/LUCIEPSC47.jpg", "https://i.ibb.co/FLLy1rLh/LUCIEPSC49.jpg", 
    "https://i.ibb.co/GvRgRB46/LUCIEPSC48.jpg", "https://i.ibb.co/wryd3Gr0/LUCIEPSC51.jpg", "https://i.ibb.co/PzmzFBxj/LUCIEPSC50.jpg", 
    "https://i.ibb.co/PZLQCCgW/LUCIEPSC52.jpg", "https://i.ibb.co/Mxb37VjR/LUCIEPSC53.jpg", "https://i.ibb.co/ycGrtfbh/LUCIEPSC54.jpg", 
    "https://i.ibb.co/MxfmmyLN/LUCIEPSC55.jpg", "https://i.ibb.co/FqdpJf5q/LUCIEPSC56.jpg", "https://i.ibb.co/9HBXydhH/LUCIEPSC57.jpg", 
    "https://i.ibb.co/846jHM40/LUCIEPSC58.jpg", "https://i.ibb.co/pBsg00LD/LUCIEPSC59.jpg", "https://i.ibb.co/yGrVpk2/LUCIEPSC60.jpg", 
    "https://i.ibb.co/5XhMcNY8/LUCIEPSC61.jpg", "https://i.ibb.co/MybxCK7y/LUCIEPSC62.jpg", "https://i.ibb.co/qHV3ch6/LUCIEPSC63.jpg", 
    "https://i.ibb.co/3yb4MYcY/LUCIEPSC64.jpg", "https://i.ibb.co/239DQ6F4/LUCIEPSC65.jpg", "https://i.ibb.co/d0nXccxj/LUCIEPSC66.jpg", 
    "https://i.ibb.co/RpJ6wFYG/LUCIEPSC67.jpg", "https://i.ibb.co/NgkT9Cgb/LUCIEPSC68.jpg", "https://i.ibb.co/0VQ0QxJc/LUCIEPSC69.jpg", 
    "https://i.ibb.co/LhYL3T6M/LUCIEPSC70.jpg", "https://i.ibb.co/rKxxg8rp/LUCIEPSC71.jpg", "https://i.ibb.co/prWfHGbm/LUCIEPSC72.jpg", 
    "https://i.ibb.co/gL7bRp0X/LUCIEPSC74.jpg", "https://i.ibb.co/QFSRG10b/LUCIEPSC73.jpg", "https://i.ibb.co/3msGhWYZ/LUCIEPSC75.jpg", 
    "https://i.ibb.co/JFgt064N/LUCIEPSC76.jpg", "https://i.ibb.co/mVc8RSv3/LUCIEPSC77.jpg", "https://i.ibb.co/ksLSJBNG/LUCIEPSC78.jpg", 
    "https://i.ibb.co/23RD858Z/LUCIEPSC79.jpg", "https://i.ibb.co/TxgVM7Qq/LUCIEPSC80.jpg", "https://i.ibb.co/7N2kr8dT/LUCIEPSC81.jpg", 
    "https://i.ibb.co/s9jdBKBy/LUCIEPSC82.jpg", "https://i.ibb.co/ccrNFJs6/LUCIEPSC83.jpg", "https://i.ibb.co/cKmvKBZ5/LUCIEPSC84.jpg", 
    "https://i.ibb.co/gNPQWnS/LUCIEPSC85.jpg", "https://i.ibb.co/zhLnnY3X/LUCIEPSC86.jpg", "https://i.ibb.co/Rk09v7fh/LUCIEPSC87.jpg", 
    "https://i.ibb.co/M5s9vFjD/LUCIEPSC88.jpg", "https://i.ibb.co/Xcqg2tX/LUCIEPSC89.jpg", "https://i.ibb.co/ynVxd2qJ/LUCIEPSC90.jpg", 
    "https://i.ibb.co/bjPzQZ42/LUCIEPSC91.jpg", "https://i.ibb.co/zWbWHSSb/LUCIEPSC92.jpg", "https://i.ibb.co/27HyPDNd/LUCIEPSC93.jpg", 
    "https://i.ibb.co/tw4XM7j7/LUCIEPSC94.jpg", "https://i.ibb.co/FL8XwD8X/LUCIEPSC95.jpg", "https://i.ibb.co/Tqn9GR3Y/LUCIEPSC96.jpg", 
    "https://i.ibb.co/wZnkDbSj/LUCIEPSC97.jpg", "https://i.ibb.co/1NwL334/LUCIEPSC98.jpg", "https://i.ibb.co/My77K57h/LUCIEPSC99.jpg"
];

export const packageData: Package[] = [
    { id: 'lucie1', name: 'LUCIE 1', price: 3500000, 
      location_details: ['STUDIO LUCIE'], 
      product_details: ['01 Ảnh khung 60x90', '01 Ảnh để bàn 20x30 ép gỗ', 'Trả toàn bộ file gốc & file chỉnh sửa.'], 
      shooting_service_details: ['01 vest tự chọn', '01 váy cưới tự chọn', 'Trang Điểm, làm tóc CD-CR', 'Hoa và phụ kiện.'], 
      wedding_service_details: ['Không áp dụng Dịch vụ ngày cưới.'],
      comp_location: 'Studio Lucie',
      comp_frame: '1 Khung 60x90',
      comp_album: 'Không Album',
      comp_video: 'Không Video',
      comp_shoot_outfits: '1 Vest, 1 Váy Cưới',
      comp_wedding_level: 'Không'
    },
    { id: 'lucie2', name: 'LUCIE 2', price: 5800000, 
      location_details: ['STUDIO LUCIE'], 
      product_details: ['02 Ảnh khung 60x90 (Ảnh Gương)', '01 Ảnh để bàn 20x30 ép gỗ', '02 Ảnh Khung', 'Trả toàn bộ file gốc & file chỉnh sửa.'], 
      shooting_service_details: ['01 vest tự chọn', '01 váy cưới tự chọn', 'Trang Điểm, làm tóc CD-CR', 'Hoa và phụ kiện.'], 
      wedding_service_details: ['01 Váy, 01 vest', 'Áo dài Dâu', 'Make up nội thành 4km.'],
      comp_location: 'Studio Lucie',
      comp_frame: '2 Khung 60x90 Gương',
      comp_album: 'Không Album',
      comp_video: 'Không Video',
      comp_shoot_outfits: '1 Vest, 1 Váy Cưới',
      comp_wedding_level: '01 Váy, 01 Vest, Áo dài Dâu. Make up 4km.'
    },
    { id: 'lucie3', name: 'LUCIE 3', price: 6800000, 
      location_details: ['STUDIO LUCIE'], 
      product_details: ['02 Ảnh khung 60x90 (Gương)', '01 Ảnh để bàn 20x30 ép gỗ', 'Album 20x30 10 Trang', '01 slide ảnh', 'Trả toàn bộ file gốc & file chỉnh sửa.'], 
      shooting_service_details: ['01 vest tự chọn', '01 váy cưới tự chọn', '01 Váy Phi tự chọn', 'Makeup làm tóc ngày chụp', '1 concept tự chọn (áo dài/cổ phục đồ đôi)', 'Hoa và phụ kiện.'], 
      wedding_service_details: ['01 Váy, 01 vest', 'Áo dài Dâu', 'Áo dài đô lẻ nữ Nơ/caravat đội đô lẻ nam', 'Make up nội thành 4km (có make up ngoại thành).'],
      comp_location: 'Studio Lucie',
      comp_frame: '2 Khung 60x90 Gương',
      comp_album: 'Album 20x30 (10 Trang)',
      comp_video: 'Video Slide',
      comp_shoot_outfits: '1 Vest, 1 Váy Cưới, 1 Váy Phi',
      comp_wedding_level: '01 Váy, 01 Vest, Áo dài Dâu. Make up 4km.'
    },
    { id: 'lucie4', name: 'LUCIE 4', price: 7900000, 
      location_details: ['STUDIO LUCIE', 'Phim trường HD', 'Ngoại cảnh nội thành HD (Miễn phí xe).'], 
      product_details: ['02 Ảnh khung 60x90 tráng gương bo góc', '01 Ảnh để bàn 20x30 ép gỗ', 'Album 20x30 15 Trang', '01 Video slide ảnh 4K', 'Trả toàn bộ file gốc & file chỉnh sửa.'], 
      shooting_service_details: ['02 vest tự chọn', '02 váy cưới tự chọn', '01 Váy Phi tự chọn', 'Makeup làm tóc ngày chụp', '1 concept tự chọn (áo dài/cổ phục đồ đôi)', 'Hoa và phụ kiện.'], 
      wedding_service_details: ['01 Váy, 01 vest', 'Áo dài CD', 'Áo dài đỏ lẻ nữ Nơ/caravat đội đô lẻ nam', 'Make up ăn hỏi + cưới (10km free có make up ngoại thành).'],
      comp_location: 'Ngoại cảnh Nội thành HD (Miễn phí xe)',
      comp_frame: '2 Khung 60x90 Tráng Gương',
      comp_album: 'Album 20x30 (15 Trang)',
      comp_video: 'Video Slide 4K',
      comp_shoot_outfits: '2 Vest, 2 Váy Cưới, 1 Váy Phi',
      comp_wedding_level: '01 Váy, 01 Vest, Áo dài CD. Make up Ăn Hỏi + Cưới (10km free).'
    },
    { id: 'lucie5', name: 'LUCIE 5', price: 8800000, 
      location_details: ['STUDIO LUCIE', 'Phim trường HD', 'Ngoại cảnh Chí Linh/Côn Sơn (Miễn phí xe).'], 
      product_details: ['02 Ảnh khung 60x90 meka HD', '01 Ảnh để bàn 20x30 ép gỗ', 'Album 20x30 15 Trang', '01 Video slide ảnh 4K', 'Trả toàn bộ file gốc & file chỉnh sửa.'], 
      shooting_service_details: ['02 vest tự chọn', '02 váy cưới tự chọn', '01 Váy cao cấp', 'Makeup làm tóc ngày chụp', '1 concept tự chọn (áo dài/cổ phục đồ đôi)', 'Hoa và phụ kiện.'], 
      wedding_service_details: ['01 Váy cao cấp, 01 vest, Nơ/caravat chú rể', 'Áo dài cặp CD&CR', 'Áo dài đỏ lẻ nam - nữ', 'Make up ăn hỏi + cưới (10km free có make up ngoại thành).'],
      comp_location: 'Ngoại cảnh Chí Linh/Côn Sơn (Miễn phí xe)',
      comp_frame: '2 Khung 60x90 Meka HD',
      comp_album: 'Album 20x30 (15 Trang)',
      comp_video: 'Video Slide 4K',
      comp_shoot_outfits: '2 Vest, 2 Váy Cưới, 1 Váy Cao cấp',
      comp_wedding_level: '01 Váy Cao cấp, Áo dài cặp CD&CR. Make up Ăn Hỏi + Cưới (10km free).'
    },
    { id: 'lucie6', name: 'LUCIE 6', price: 11000000, 
      location_details: ['STUDIO LUCIE', 'Phim trường Hà Nội (santorini park, 5graden, smile valley..v.v.)', 'Ngoại cảnh Hà Nội/Uông Bí/Hạ Long.'], 
      product_details: ['02 Khung 60x90 meka HD', '01 Ảnh để bàn 20x30 ép gỗ', 'Album 20x30 20 Trang', '01 Video slide ảnh 4K', 'Trả toàn bộ file gốc & file chỉnh sửa.'], 
      shooting_service_details: ['02 vest tự chọn', '01 váy cưới tự chọn', '02 Váy cao cấp', 'Makeup làm tóc ngày chụp', '2 concept tự chọn (áo dài/cổ phục đồ đôi)', 'Hoa và phụ kiện.'], 
      wedding_service_details: ['01 Váy cao cấp, 01 vest, Nơ/caravat chú rể', 'Áo dài cặp cao cấp CD&CR', 'Áo dài đỏ lẻ nam nữ (tuỳ số lượng)', 'Make up ăn hỏi + cưới (10km free có make up ngoại thành).'],
      comp_location: 'Ngoại cảnh HN/Uông Bí/Hạ Long',
      comp_frame: '2 Khung 60x90 Meka HD',
      comp_album: 'Album 20x30 (20 Trang)',
      comp_video: 'Video Slide 4K',
      comp_shoot_outfits: '2 Vest, 1 Váy Cưới, 2 Váy Cao cấp',
      comp_wedding_level: '01 Váy Cao cấp, Áo dài cặp Cao cấp CD&CR. Make up Ăn Hỏi + Cưới (10km free).'
    },
    { id: 'lucie7', name: 'LUCIE 7', price: 12500000, 
      location_details: ['STUDIO LUCIE', 'Phim trường Hà Nội', 'Ngoại cảnh Hà Nội/Uông Bí/Hạ Long.'], 
      product_details: ['01 Khung 60x90 meka HD', '01 Khung 60x120 meka HD', '01 Ảnh để bàn 20x30 ép gỗ', 'Bộ khung VIP 12 ảnh (Album 30x30 20 Trang)', '01 Video slide ảnh 4K', 'Trả toàn bộ file gốc & file chỉnh sửa.'], 
      shooting_service_details: ['02 vest tự chọn', '01 váy cưới tự chọn', '02 Váy cao cấp', 'Makeup làm tóc ngày chụp', '2 concept tự chọn (áo dài/cổ phục đồ đôi)', 'Hoa và phụ kiện.'], 
      wedding_service_details: ['01 Váy limited', '01 váy phí đi bàn', '01 vest, Nơ/caravat chú rể', 'Áo dài cặp cao cấp CD&CR', 'Áo dài đỡ lẻ nam nữ (tuỳ số lượng)', 'Make up ăn hỏi + cưới (10km free có make up ngoại thành).'],
      comp_location: 'Ngoại cảnh HN/Uông Bí/Hạ Long',
      comp_frame: '1 Khung 60x90 + 1 Khung 60x120',
      comp_album: 'Album 30x30 (20 Trang) + Bộ 12 ảnh',
      comp_video: 'Video Slide 4K',
      comp_shoot_outfits: '2 Vest, 1 Váy Cưới, 2 Váy Cao cấp',
      comp_wedding_level: '01 Váy Limited, 01 Váy Phi đi bàn. Áo dài cặp Cao cấp.'
    },
    { id: 'lucie8', name: 'LUCIE 8', price: 15500000, 
      location_details: ['STUDIO LUCIE', 'Phim trường Hà Nội', 'Ngoại cảnh Quảng Ninh/Tam Đảo/Ninh Bình/Đại Lải.'], 
      product_details: ['02 Ảnh khung 60x90 Gương 4K Khung Kim loại', '02 Ảnh để bàn 20x30 ép gỗ', 'Bộ khung VIP 15 ảnh (Album 30x30 30 Trang)', '01 Video slide ảnh 4K', 'Trả toàn bộ file gốc & file chỉnh sửa.'], 
      shooting_service_details: ['02 vest tự chọn', '02 váy cưới tự chọn', '01 Váy limited', 'Makeup làm tóc ngày chụp', '2 concept tự chọn (áo dài/cổ phục đồ đôi)', 'Hoa và phụ kiện.'], 
      wedding_service_details: ['01 Váy limited', '01 váy phí đi bàn', '01 vest, Nơ/caravat chú rể', 'Áo dài cặp cao cấp CD&CR', 'Áo dài đỏ lẻ nam nữ (tuỳ số lượng)', 'Make up ăn hỏi + cưới (10km free có make up ngoại thành).'],
      comp_location: 'Ngoại cảnh QN/Tam Đảo/NB/ĐL',
      comp_frame: '2 Khung 60x90 Gương 4K Khung Kim loại',
      comp_album: 'Album 30x30 (30 Trang) + Bộ 15 ảnh VIP',
      comp_video: 'Video Slide 4K',
      comp_shoot_outfits: '2 Vest, 2 Váy Cưới, 1 Váy Limited',
      comp_wedding_level: '01 Váy Limited, 01 Váy Phi đi bàn. Áo dài cặp Cao cấp.'
    },
    { id: 'lucievip', name: 'LUCIE VIP', price: 26500000, 
      location_details: ['STUDIO LUCIE', 'Phim trường Hà Nội', 'Ngoại cảnh QN/Tam Đảo/NB/Đại Lải/Cô Tô/Quan Lạn.'], 
      product_details: ['02 Ảnh khung 60x90 Gương 4K Khung Kim loại', '01 Ảnh khung 60x120 meka HD', '02 Ảnh để bàn 20x30 ép gỗ', 'Bộ khung VIP 15 ảnh (Album 4K 30x30 30 Trang)', '01 Video slide ảnh 4K', '01 Video prewedding', 'Trả toàn bộ file gốc & file chỉnh sửa.'], 
      shooting_service_details: ['03 vest tự chọn', '02 váy cưới tự chọn', '02 Váy limited', 'Makeup làm tóc ngày chụp', '2 concept tự chọn (áo dài/cổ phục đồ đôi)', 'Hoa tươi và phụ kiện.'], 
      wedding_service_details: ['01 Váy thiết kế cao cấp theo số đo', '01 váy phí đi bàn', '01 vest, Nơ/caravat chú rể', 'Áo dài cặp cao cấp CD&CR', 'Áo dài đỏ lẻ nam nữ (tuỳ số lượng)', 'Make up ăn hỏi + cưới (10km free có make up ngoại thành).'],
      comp_location: 'Ngoại cảnh QN/TĐ/NB/ĐL/Cô Tô/QL',
      comp_frame: '2 Khung 60x90 Gương 4K Khung Kim loại + 1 Khung 60x120',
      comp_album: 'Album 4K 30x30 (30 Trang) + Bộ 15 ảnh VIP',
      comp_video: 'Video Slide 4K + Video Prewedding',
      comp_shoot_outfits: '3 Vest, 2 Váy Cưới, 2 Váy Limited',
      comp_wedding_level: '01 Váy Thiết kế theo số đo. Áo dài cặp Cao cấp.'
    },
    { id: 'combo1', name: 'PACKCOMBO 1', price: 11000000, isCombo: true, 
      location_details: ['STUDIO LUCIE', 'Phim trường HD', 'Ngoại cảnh nội thành HD (Miễn phí xe).'], 
      product_details: ['Toàn bộ Sản phẩm Ảnh của gói LUCIE 4.'], 
      shooting_service_details: ['Toàn bộ Dịch vụ Ngày Chụp của gói LUCIE 4.'], 
      wedding_service_details: [
        '01 Váy, 01 vest', 'Áo dài CD', 'Áo dài đô lẻ nữ Nơ/caravat đội đô lẻ nam, Make up ăn hỏi + cưới (10km free có make up ngoại thành).', 
        'Bổ sung: 01 máy chụp ảnh lẻ Lễ Ăn hỏi + Lễ Cưới.'
      ],
      comp_location: 'Ngoại cảnh Nội thành HD', 
      comp_frame: '2 Khung 60x90 Tráng Gương',
      comp_album: 'Album 20x30 (15 Trang)',
      comp_video: 'Video Slide 4K',
      comp_shoot_outfits: '2 Vest, 2 Váy Cưới, 1 Váy Phi',
      comp_wedding_level: 'Gói LUCIE 4 (Wedding) + 1 máy chụp Lễ Ăn hỏi/Cưới.'
    },
    { id: 'combo2', name: 'PACKCOMBO 2', price: 12000000, isCombo: true, 
      location_details: ['STUDIO LUCIE', 'Phim trường HD', 'Ngoại cảnh Chí Linh/Côn Sơn (Miễn phí xe).'], 
      product_details: ['Toàn bộ Sản phẩm Ảnh của gói LUCIE 5.'], 
      shooting_service_details: ['Toàn bộ Dịch vụ Ngày Chụp của gói LUCIE 5.'], 
      wedding_service_details: [
        '01 Váy cao cấp, 01 vest, Nơ/caravat chú rể, Áo dài cặp CD&CR, Áo dài đỏ lẻ nam - nữ, Make up ăn hỏi + cưới (10km free có make up ngoại thành).',
        'Bổ sung: 01 máy chụp ảnh lẻ Lễ Ăn hỏi + Lễ Cưới.'
      ],
      comp_location: 'Ngoại cảnh Chí Linh/Côn Sơn', 
      comp_frame: '2 Khung 60x90 Meka HD',
      comp_album: 'Album 20x30 (15 Trang)',
      comp_video: 'Video Slide 4K',
      comp_shoot_outfits: '2 Vest, 2 Váy Cưới, 1 Váy Cao cấp',
      comp_wedding_level: 'Gói LUCIE 5 (Wedding) + 1 máy chụp Lễ Ăn hỏi/Cưới.'
    },
    { id: 'combo3', name: 'PACKCOMBO 3', price: 14000000, isCombo: true, 
      location_details: ['STUDIO LUCIE', 'Phim trường Hà Nội', 'Ngoại cảnh Hà Nội/Uông Bí/Hạ Long.'], 
      product_details: ['Toàn bộ Sản phẩm Ảnh của gói LUCIE 6.'], 
      shooting_service_details: ['Toàn bộ Dịch vụ Ngày Chụp của gói LUCIE 6.'], 
      wedding_service_details: [
        '01 Váy cao cấp, 01 vest, Nơ/caravat chú rể, Áo dài cặp cao cấp CD&CR', 'Áo dài đỏ lẻ nam nữ (tuỳ số lượng)', 'Make up ăn hỏi + cưới (10km free có make up ngoại thành).',
        'Bổ sung: 01 máy chụp ảnh lẻ Lễ Ăn hỏi + Lễ Cưới.'
      ],
      comp_location: 'Ngoại cảnh HN/Uông Bí/Hạ Long', 
      comp_frame: '2 Khung 60x90 Meka HD',
      comp_album: 'Album 20x30 (20 Trang)',
      comp_video: 'Video Slide 4K',
      comp_shoot_outfits: '2 Vest, 1 Váy Cưới, 2 Váy Cao cấp',
      comp_wedding_level: 'Gói LUCIE 6 (Wedding) + 1 máy chụp Lễ Ăn hỏi/Cưới.'
    }
];

export function formatCurrency(value: number) {
    return new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(value);
}
